#!/usr/bin/env python

import argparse
import os

import conf
import theme
import utils


themes = []
themes_dic = {}

c = conf.config()

# This loop goes through the data from the yaml file
# it iterates over the attributes for theme, currently colorscheme, wallpaper, and color
# it then sets a local var to these items and uses it to make a Theme var
# The theme var is stored in an array and a dictionary
for name in c.data["themes"]:
    loc_vars = locals()
    for att in theme.Theme.attributes:
        try:
            loc_vars.__setitem__(att,c.data["themes"][name][att])
        except (KeyError, TypeError):
            loc_vars.__setitem__(att,None)

    if type(time).__name__ != 'list':
        time = [time]

    for ti in time:
        t = theme.Theme(name, colorscheme, icontheme, wallpaper, command, ti )

        themes_dic[name] = t
        themes.append(t)

#themes = sorted(themes)
themes = sorted(themes, reverse=True)

###################################
# IO Functions
###################################

# Writes the timers/services for each timed theme
def write_timer():

    os.system(f'rm {c.systemd_loc}kshift*')

    for theme in themes:

        if theme.time:
            file = open(c.systemd_loc+"kshift-"+theme.name+".timer","w")
            file.write("[Unit]\nDescription=kshift timer for theme:"+theme.name+"\n\n[Timer]\n")

            # Will need to change to just OnCalendar times
            #time = theme.time.strftime("%H:%M")
            #file.write("OnCalendar=*-*-* "+time+":00\n")
            file.write(f'OnCalendar={theme.time}\n')

            file.write("Persistent=true\n\n[Install]\nWantedBy=timers.target")
            file.close()

            file = open(c.systemd_loc+"kshift-"+theme.name+".service","w")
            exec_name = os.path.basename(__file__)

            file.write("[Unit]\nDescription=kshift service\n\n[Service]\nExecStart="+c.home+"/.local/bin/"+exec_name+" -t "+theme.name)
            file.close()

    os.system("systemctl --user daemon-reload")

    for theme in themes:
        if theme.time:
            os.system("systemctl --user enable kshift-"+theme.name+".timer")
            os.system("systemctl --user restart kshift-"+theme.name+".timer")


# Installs kshift
# Copies executable, creates config file, utilizes the write timer func, and enables the timer
def install():

    exec_name = os.path.basename(__file__)

    print("Linking Kshift to .local/bin...")
    os.makedirs(c.home+"/.local/bin/", exist_ok=True)

    os.system("ln -s -f "+__file__+" "+c.home+"/.local/bin/"+exec_name)

    var_loc = c.config_loc
    # Make config dir, possibly read config env
    if not os.path.exists(c.config_loc_base):
        os.makedirs(c.config_loc_base)

    if not os.path.exists(var_loc):
        print("Copying 'defaults.yml' to"+ var_loc+"...")
        os.system("cp defaults.yml "+var_loc)

    os.makedirs(c.systemd_loc, exist_ok=True)

    print("Writing theme timers and services...")

    write_timer()

    print("Enabling services...")


# Removes Kshift timer
def remove_self():

    print("Removing kshift timers and services...")

    os.system("rm "+c.systemd_loc+"kshift-*")

    os.system("systemctl --user daemon-reload")

###################################
# Arg parsing
###################################

parser = argparse.ArgumentParser(description="KDE Theme Switching")

parser.add_argument("-w", "--wallpaper", help="Sets the current wallpaper", type=str, required=False)
parser.add_argument("-c","--colorscheme", type=str,help="Sets the colorscheme", required=False)
parser.add_argument("-i","--icontheme", type=str,help="Sets the icon theme", required=False)
parser.add_argument("-t", "--theme", help="Sets the theme", type=str, choices=list(c.data["themes"].keys()), required=False)


# These cannot be called together
install_g = parser.add_mutually_exclusive_group(required=False)
install_g.add_argument("--install", help="Installs Kshift", action="store_true")
install_g.add_argument("--remove", help="Removes Kshift", action="store_true")
install_g.add_argument("-s", "--status", help="Displays kshift timing information", action='store_true')


args = parser.parse_args()

if args.status:

    c.status()

elif args.install:

    answer = input("Are you sure you want to install Kshift? [y/n]: ")
    if answer == "Y" or answer == "y" or answer == "yes":
        install()

elif args.remove:

    answer = input("Are you sure you want to remove Kshift? [y/n]: ")
    if answer == "Y" or answer == "y" or answer == "yes":
        remove_self()

else:

    if args.theme:
        themes_dic[args.theme].kshift()

    elif args.colorscheme or args.icontheme or args.wallpaper:
        theme.Theme("tmp", args.colorscheme, args.icontheme, args.wallpaper, None, None).kshift()

    else:

        theme_to_be = None

        # if the time is >= the theme time, it should be that one to switch
        # if none is greater, then do nothing.
        for theme in themes:

            if theme.time is None:
                break
            elif c.today >= utils.systemd_to_datetime(theme.time, c.today):
                theme_to_be = theme
                break

        if theme_to_be:
            theme_to_be.kshift()

    write_timer()
